name: playwright

on:
  pull_request:

jobs:
  e2e-playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-and-install

      - run: pnpm nx run-many -t e2e

      - uses: ./.github/actions/debug

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: dist/.playwright/
          retention-days: 1
