name: playwright

on:
  pull_request:
  push:
    branches:
      - ci/improve-time-usage

jobs:
  e2e-playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-and-install

      - run: pnpm nx run-many -t e2e

      - run: ls -a
        if: always()

      - run: |
          if [ -d dist ]; then find dist -type f; else echo "dist/ directory does not exist."; fi
        if: always()

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1
