name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - 'helpers@*.*.*'
      - 'react-lib@*.*.*'

jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write # needed for provenance data generation
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v4

      - run: pnpm nx run-many -t build -p helpers react-lib

      - name: Publish packages
        run: pnpm nx release publish -p helpers react-lib
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
