name: push-main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      id-token: write # needed for provenance data generation
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-and-install

      - name: Configure npm for authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" > ~/.npmrc
          echo "access=public" >> ~/.npmrc

      - name: Verify npm authentication
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - uses: nrwl/nx-set-shas@v4

      - run: pnpm nx run-many -t build -p helpers react-lib

      - name: Publish packages
        run: pnpm nx release -y -p helpers react-lib
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Push Tag
        if: always()
        run: git push origin main --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
